#!/bin/sh

cd $(dirname $0)
source $(dirname $0)/config

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

bspc control --subscribe > "$PANEL_FIFO" &
xtitle -sf 'T%s' > "$PANEL_FIFO" &
./time > "$PANEL_FIFO" &

cat "$PANEL_FIFO" \
    | ./panel_bar \
    | lemonbar \
        -f "$FONT" \
        -F "$COLOR_FOREGROUND" \
        -B "$COLOR_BACKGROUND" \
        -a 30 \
        -u 3

wait
