#! /bin/bash

cd $(dirname $0)

sxhkd &
panel/panel &
stalonetray &
nm-applet &
compton -f &
./noctrl.sh
./xinput.sh
cat $HOME/.fehbg | bash

bspc config border_width        2
bspc config window_gap         12

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc monitor -d 1 2 3 4 5

bspc rule -a Gimp desktop=^8 state=floating follow=on
bspc rule -a Chromium desktop=^2
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
