#! /bin/bash

bspc config border_width        2
bspc config window_gap          12
bspc config top_padding         25

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

#i=1
#for monitor in $(bspc query -M); do
#    bspc monitor $monitor \
#        -n "$i" \
#        -d I II III IV V VI VII VIII IX X
#    let i++
#done

bspc monitor DVI-0 -n 1 -d I II III IV V
bspc monitor DVI-1 -n 2 -d VI VII VIII IX X

bspc rule -a Gimp desktop=^8 follow=on floating=on
bspc rule -a Chromium desktop=^2
bspc rule -a mplayer2 floating=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc rule -a Spotify pseudo_tiled=on
bspc rule -a Steam pseudo_tiled=on
bspc rule -a feh floating=on manage=off

cat ~/.fehbg | bash


