#. /home/local/ALLEGROGROUP/marcin.radoszewski/.nix-profile/etc/profile.d/nix.sh
#
export PATH="$PATH:/home/morti/bin:/home/morti/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/share/java/gradle/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/morti/.gem/ruby/2.4.0/bin:$HOME/bin"

