#!/bin/sh

INSTANCE="${1:-BAT0}"
ALERT_LOW="${2:-20}"

if test -e "/sys/class/power_supply/$INSTANCE"
then
    status=$(cat /sys/class/power_supply/$INSTANCE/status)
    capacity=$(cat /sys/class/power_supply/$INSTANCE/capacity)

    case "$status" in
        "Discharging")
            symbol='↓'
            ;;
        "Charging")
            symbol='↑'
            ;;
        "Full")
            exit
            ;;
    esac

    bat=

    if [ "$capacity" -gt "20" ]; then
        bat=
    fi

    if [ "$capacity" -gt "40" ]; then
        bat=
    fi

    if [ "$capacity" -gt "60" ]; then
        bat=
    fi

    if [ "$capacity" -gt "80" ]; then
        bat=
    fi

    # Full text
    echo "$bat $capacity% $symbol"

    # Short text
    echo "$bat $capacity% $symbol"

    # Color
    if test $capacity -le $ALERT_LOW -a $status = "Discharging"
    then
        echo "#FF0000"
    fi
fi
