- name: Arch Configuration
  hosts: localhost
  tasks:
    - name: Install required packages
      pacman:
        name:
          - stow
          - zsh
          - xsel
          - neovim
          - tmux
          - fzf
          - eza
          - ripgrep
          - bat
          - starship
          - unzip
          - git-delta
          - github-cli
          - fontconfig
          - ttf-jetbrains-mono-nerd
          - zoxide
          - alacritty
          - rofi
          - i3blocks
        state: latest
        update_cache: yes
      become: true

    - name: Install vinote
      ansible.builtin.shell:
        cmd: go install github.com/marad/vinote/cmd/vn@latest
        creates: ~/go/bin/vn

    - name: Set default shell to zsh
      become: true
      ansible.builtin.user:
        name: "{{ ansible_user_id }}"
        shell: /usr/bin/zsh
