- name: macOS Configuration
  hosts: localhost
  tasks:
    - name: Install Homebrew packages
      community.general.homebrew:
        name:
          - stow
          - neovim
          - neovide
          - tmux
          - fzf
          - fd
          - eza
          - ripgrep
          - bat
          - jq
          - tree
          - watch
          - parallel
          - starship
          - tree-sitter
          - gh
          - go
          - git-delta
          - node
          - ical-buddy
          - podman-compose
          - zoxide
        state: present

    - name: Install Homebrew cask packages
      community.general.homebrew_cask:
        name:
          - font-jetbrains-mono-nerd-font
          - alacritty
          - karabiner-elements
          - podman-desktop
          - gcloud-cli
        state: present

    - name: Install vinote
      ansible.builtin.shell:
        cmd: go install github.com/marad/vinote/cmd/vn@latest
        creates: ~/go/bin/vn
