- name: Ubuntu Configuration
  hosts: localhost
  tasks:
    - name: Install required apt packages
      apt:
        name:
          - stow
          - zsh
          - curl
          - tmux
          - xsel
          - fzf
          - unzip
          - zip
          - fontconfig
          - libfontconfig-dev
          - build-essential
          - cmake
          - tree
          - gh
          - ripgrep
          - eza
          - bat
          - zoxide
          - git-delta
          - feh
          - i3blocks
          - waybar
          - grim
          - slurp
          - swaylock
          - swayidle
          - swaybg
          - wl-clipboard
          - rofi
          - playerctl
          - cliphist
          - xdg-desktop-portal-gtk
        state: latest
      become: true

    - name: Install starship prompt
      ansible.builtin.shell:
        cmd: curl -sS https://starship.rs/install.sh | sh -s -- -y
        creates: /usr/local/bin/starship

    - name: Install vinote
      ansible.builtin.shell:
        cmd: go install github.com/marad/vinote/cmd/vn@latest
        creates: ~/go/bin/vn

    - name: Make sure that apt neovim package is absent
      become: true
      apt:
        name:
          - neovim
          - neovim-qt
          - neovim-runtime
        state: absent

    - name: Make sure that snap neovim package is absent
      become: true
      snap:
        name:
          - nvim
          - nvim-gtk
        state: absent

    - name: Install neovim
      become: true
      ansible.builtin.script:
        cmd: ../scripts/install_nvim.sh
        creates: /opt/nvim-linux-x86_64

    - name: Install node version manager
      ansible.builtin.shell:
        cmd: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash
        creates: ~/.nvm

    - name: Install latest nodejs with NVM
      ansible.builtin.shell:
        cmd: bash -c 'source ~/.nvm/nvm.sh && nvm install node'
        creates: ~/.npm

    - name: Install tldr command
      ansible.builtin.shell:
        cmd: bash -c 'source ~/.nvm/nvm.sh && npm install -g tldr'

    - name: Install sdkman
      ansible.builtin.shell:
        cmd: curl -s "https://get.sdkman.io" | bash
        creates: ~/.sdkman

    - name: Install Hyprland
      become: true
      ansible.builtin.script:
        cmd: ../scripts/install_hyprland.sh
        creates: /usr/bin/Hyprland

    - name: Set default shell to zsh
      become: true
      ansible.builtin.user:
        name: "{{ ansible_user_id }}"
        shell: /usr/bin/zsh
